version: 1
disable_existing_loggers: False

formatters:
  with_time:
    format: "%(asctime)s - %(levelname)s - %(name)s - %(message)s"
  with_user:
    format: "%(asctime)s - %(levelname)s - %(name)s - User: %(user)s - %(message)s"

handlers:
  file:
    class: logging.FileHandler
    filename: "history.log"
    formatter: with_time
    level: DEBUG
  file_with_user:
    class: logging.FileHandler
    filename: "history.log"
    formatter: with_user
    level: INFO

loggers:
  uvicorn:
    handlers: [file]
    level: DEBUG
    propagate: False

  uvicorn.error:
    handlers: [file]
    level: DEBUG
    propagate: False

  uvicorn.access:
    handlers: [file]
    level: DEBUG
    propagate: False

  conversation:
    handlers: [file_with_user]
    level: INFO
    propagate: False

root:
  handlers: [file]
  level: DEBUG
